language: python

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=false
        - EXTRATESTERS="mock"
        - ARGS="--verbose"
    - python: 3.4
      env:
        - COVERAGE=false
        - EXTRATESTERS=""
        - ARGS="--mpl --verbose"
    - python: 3.5
      env:
        - COVERAGE=true
        - EXTRATESTERS=""
        - ARGS="--mpl --verbose"
    - python: 3.6
      env:
        - COVERAGE=false
        - EXTRATESTERS=""
        - ARGS="--mpl --verbose --pep8"

before_install:

  # Here we just install Miniconda, which you shouldn't have to change.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda install --yes nomkl

install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION numpy matplotlib docopt requests pyyaml
  - source activate test
  - conda install --yes --channel=conda-forge pytest-mpl pytest-cov pytest-pep8 ${EXTRATESTERS}
  - if [ ${COVERAGE} = true ]; then conda install scipy --yes; fi
  - pip install codecov
  - pip install .

script:
  - python check_probscale.py ${ARGS}

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage run --source probscale check_probscale.py;
      coverage report -m;
      codecov;
    fi
