package:
  name: mpl-probscale
  version: 0.1.1

source:
  path: ../../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - matplotlib

  run:
    - python
    - numpy
    - matplotlib
    - nose

test:
  imports:
    - probscale

  commands:
    - python -c "import matplotlib; matplotlib.use('agg'); import probscale; probscale.test()"

  requires:
    - nose
    - scipy

about:
  home: http://phobson.github.io/mpl-probscale/
  license:  BSD License
  summary: 'Probability scales for matplotlib.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
