package:
  name: mpl-probscale
  version: 0.2.0dev

source:
  path: ../

build:
  script: python setup.py install
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib

  run:
    - python
    - numpy
    - matplotlib
    - pytest

test:
  imports:
    - probscale

  commands:
    - python -c "import matplotlib as mpl; mpl.use('agg'); import probscale as ps; ps.test()"

  requires:
    - pytest
    - scipy

about:
  home: http://phobson.github.io/mpl-probscale/
  license:  BSD License
  summary: 'Probability scales for matplotlib.'
