package:
  name: mpl-probscale
  version: v0.1.0

source:
  git_url: https://github.com/phobson/mpl-probscale.git
  git_tag: v0.1.0
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - matplotlib

  run:
    - python
    - numpy
    - matplotlib

test:
  imports:
    - probscale

  commands:
    - nosetests

  requires:
    - nose
    - scipy

about:
  home: http://phobson.github.io/mpl-probscale/
  license:  BSD License
  summary: 'Probability scales for matplotlib.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml/configure
