package:
  name: mpl-probscale
  version: 0.1.2dev

source:
  path: ../

build:
  script: python setup.py install
  number: 2

requirements:
  build:
    - python
    - numpy
    - matplotlib
    - nose

  run:
    - python
    - numpy
    - matplotlib
    - nose

test:
  imports:
    - probscale

  commands:
    - python -c "import matplotlib; matplotlib.use('agg'); import probscale; probscale.test()"

  requires:
    - nose
    - scipy

about:
  home: http://phobson.github.io/mpl-probscale/
  license:  BSD License
  summary: 'Probability scales for matplotlib.'
